logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.context=DEBUG
logging.level.org.springframework.beans=DEBUG
logging.level.org.example.weblab4=DEBUG

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/weblab4
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mvc.log-request-details=true

# Настройки для отладки
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.web.servlet.handler.SimpleUrlHandlerMapping=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter=TRACE 